spring:
  cloud:
    stream:
      function:
        definition: processor
      bindings:
        processor-in-0: # входной канал Producer; 0 - это № Partition, откуда читаются сообщения
          destination: numbers  # названия Topic, откуда читаются сообщения
        # выходной канал Producer; 0 - это № Partition, куда публикуются обработанные сообщения
        processor-out-0:
            destination: squares  # названия Topic, куда публикуются обработанные сообщения
server:
  port: 8086